services:
  wintercode-bo:
    container_name: wintercode-bo
    build:
      context: ./main
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ../shared/.env.prod
    ports:
      - "3001:3000"
    networks:
      - frostNet

networks:
  frostNet:
    external: true
# networks:
#   frostNet:
#     driver: bridge
#     attachable: true
# correct deployment
